// Modulo_5/casas-rurales-next/src/pods/house-list/components/card/card.tsx
import Image from "next/image";
import { House as HouseVM } from "@/pods/house-list";
import style from "./card.module.scss";
import Link from "next/link";
import { routes } from "@/core/constants";
import { MarkReserved } from "../reserved-marked";
import { useContextReserved } from "@/hooks/useContextReserved";
import { BathroomsIcon, BedIcon, BedroomsIcon } from "@/components/icons";
import { ShowRating } from "@/components/show-rating";
interface Props {
  house: HouseVM;
}

export const Card: React.FC<Props> = ({ house }) => {
  const { getIsReserve } = useContextReserved();
  const isReserve = getIsReserve(house.id);
  return (
    <article className={style.card}>
      <Link
        href={`${routes.detalle}/${house.id}`}
        aria-label={`Ir a página de detalle de ${house.name}`}
      >
        <div className={style.image}>
          <Image
            src={house.image}
            width={340}
            height={340}
            className={isReserve ? style.isReserved : ""}
            style={{ objectFit: "cover" }}
            alt={`${house.name}. Ubicada en ${house.address}, ${house.city}. ${isReserve ? "Estado: Reservada" : ""} `}
            loading="eager"
          />
          {isReserve && <MarkReserved />}
          <div className={style.rating}>
            <ShowRating
              rating={house.rating}
              totalReviews={house.totalReviews}
            />
          </div>
        </div>
        <footer className={style.content}>
          <span className={style.name}>{house.name}</span>
          <span
            className={style.address}
          >{`${house.address} (${house.city})`}</span>
          <div className={style.details}>
            <div
              aria-label="Número de habitaciones"
              title={`${house.bedrooms} habitaciones`}
            >
              <BedroomsIcon />
              <span>{house.bedrooms}</span>
            </div>
            <div
              aria-label="Número de baños"
              title={`${house.bathrooms} baños`}
            >
              <BathroomsIcon />
              <span>{house.bathrooms}</span>
            </div>
            <div aria-label="Número de camas" title={`${house.beds} camas`}>
              <BedIcon /> <span>{house.beds}</span>
            </div>
          </div>
          <div>
            <span className={style.price}>{`${house.price}€`}</span>
            <span className={style.labelNight}>/noche</span>
          </div>
        </footer>
      </Link>
    </article>
  );
};

// Modulo_5/casas-rurales-nuxt/app/pods/HouseListPod/components/Card.vue
<script setup lang="ts">
import ShowRating from "~/components/ShowRating.vue";
import MarkReserved from "./MarkReserved.vue";
import type { House } from "~/types/house";
import { useReservedStore } from "~/stores/reservedStore";

const props = defineProps<{
  house: House;
}>();

const { getIsReserve } = useReservedStore();
const isReserve = getIsReserve(props.house.id);
</script>
<template>
  <article class="card">
    <NuxtLink
      :href="`/detalle/${house.id}`"
      aria-label="Ir a página de detalle de {{house.name}}"
    >
      <div class="imageContent">
        <NuxtImg
          :src="house.image"
          width="340"
          height="340"
          :class="isReserve ? 'image isReserve' : 'image'"
          style="object-fit: cover"
          :alt="`${house.name}. Ubicada en ${house.address}, ${house.city}.`"
        />
        <MarkReserved v-if="isReserve" />
        <div class="rating">
          <ShowRating
            :rating="house.rating"
            :totalReviews="house.totalReviews"
          />
        </div>
      </div>
      <footer class="content">
        <span class="name">{{ house.name }}</span>
        <span class="address">{{ `${house.address} (${house.city})` }}</span>
        <div class="details">
          <div
            aria-label="Número de habitaciones"
            :title="`${house.bedrooms} habitaciones`"
          >
            <IconsBedrooms />
            <span>{{ house.bedrooms }}</span>
          </div>
          <div aria-label="Número de baños" :title="`${house.bathrooms} baños`">
            <IconsBathrooms />
            <span>{{ house.bathrooms }}</span>
          </div>
          <div aria-label="Número de camas" :title="`${house.beds} camas`">
            <IconsBed /> <span>{{ house.beds }}</span>
          </div>
        </div>
        <div>
          <span class="price">{{ `${house.price}€` }}</span>
          <span class="labelNight">/noche</span>
        </div>
      </footer>
    </NuxtLink>
  </article>
</template>

<style lang="scss" scoped>
.card {
  display: flex;
  flex-direction: column;
  align-items: center;
  flex-grow: 1;

  .imageContent {
    position: relative;
    .image {
      border-radius: $radius;
      mask-image: linear-gradient(to bottom, $background 60%, transparent 100%);
      -webkit-mask-image: linear-gradient(
        to bottom,
        $background 60%,
        transparent 100%
      );
    }
    .rating {
      position: absolute;
      bottom: 15px;
      right: 15px;
    }
  }

  .content {
    display: flex;
    flex-direction: column;
    padding: 0.6em 0.4em;
    font-size: $fs-sm;
    row-gap: 0.4em;

    .name {
      font-size: 1.1em;
      font-weight: 500;
    }
    .address {
      font-size: 0.7em;
      color: $color-700;
    }
    .price {
      font-weight: 600;
      color: $text;
    }
    .labelNight {
      font-size: 0.7em;
      color: $text;
    }

    .details {
      display: flex;
      flex-direction: row;
      gap: 1em;
      //color: #d1d1d1;
      color: $primary-color;

      span {
        padding-left: 5px;
      }
    }
  }
}

.isReserved {
  opacity: 0.5;
}
</style>
