// Modulo_5/casas-rurales-next/src/components/show-rating.tsx
import { StarFillIcon, StarEmptyIcon, StarHalfIcon } from "@/components/icons";

interface Props {
  rating: number;
  totalReviews?: number;
}
export const ShowRating: React.FC<Props> = ({ rating, totalReviews }) => {
  return (
    <div
      role="img"
      aria-label={`Calificación de ${rating} de 5 estrellas`}
      style={{ display: "flex", justifyContent: "center", fontSize: "1.2em" }}
    >
      {Array.from({ length: 5 }, (v, i) =>
        i < Math.floor(rating) ? (
          <StarFillIcon key={i} />
        ) : i < rating ? (
          <StarHalfIcon key={i} />
        ) : (
          <StarEmptyIcon key={i} />
        ),
      )}
      {totalReviews ? <span>({totalReviews})</span> : ""}
    </div>
  );
};

// Modulo_5/casas-rurales-nuxt/app/components/ShowRating.vue
<script setup lang="ts">
defineProps<{
  rating: number;
  totalReviews?: number;
}>();
</script>

<template>
  <div
    role="img"
    :aria-label="`Calificación de ${rating} de 5 estrellas`"
    class="rating"
  >
    <span v-for="i in 5" :key="i">
      {{ i <= Math.floor(rating) ? "★" : "☆" }}
    </span>
    <span v-if="totalReviews">({{ totalReviews }})</span>
  </div>
</template>

<style lang="scss" scoped>
.rating {
  display: flex;
  justify-content: center;
  font-size: 1.2em;
}
</style>
